# cf) https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

registries:
  ecr-public:
    type: docker-registry
    url: public.ecr.aws

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
      day: friday
    groups:
      aws-sdk-group:
        patterns:
          - "@aws-sdk/*"
      vitest-group:
        patterns:
          - "vitest"
          - "@vitest/*"
      eslint-group:
        patterns:
          - eslint
          - eslint-config-prettier
          - globals
          - typescript-eslint
          - "@eslint/*"
          - "@nuxt/eslint"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: friday
    registries:
      - "*"
