# cf) https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependabot
      - github_actions
    cooldown:
      default-days: 3

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependabot
      - dependencies
    groups:
      aws-sdk-group:
        patterns:
          - "@aws-sdk/*"
      vitest-group:
        patterns:
          - "vitest"
          - "@vitest/*"
      eslint-group:
        patterns:
          - eslint
          - eslint-config-prettier
          - globals
          - typescript-eslint
          - "@eslint/*"
          - "@nuxt/eslint"
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependabot
      - docker
    cooldown:
      default-days: 3
