service: avshare3

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-northeast-1
  memorySize: 1024
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::jp-live-bruin-iwai-audio-video/*
  deploymentBucket:
    name: jp-live-bruin-iwai-serverlessdeploymentbucket
    blockPublicAccess: true
  logRetentionInDays: 14

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

custom:
  credentials: ${ssm:/aws/reference/secretsmanager/avshare3/credentials}
  prune:
    automatic: true
    number: 3

functions:
  handler:
    handler: src/lambda.handler
    url: true
    environment:
      BUCKET_NAME: jp-live-bruin-iwai-audio-video
      USERNAME: ${self:custom.credentials.username}
      PASSWORD: ${self:custom.credentials.password}
