on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

# 同時に動くワークフローは1個だけ；先行ワークフローは自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-app
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - name: Build api
        run: npm run build -w @avshare3/api
      - name: Build gui
        run: npm run generate -w @avshare3/gui
      - run: npm run format
      - run: npm run lint
      - run: npm run test

  build_and_push:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # docker 系アクションは github context を直接参照するので checkout 不要だが、
      # sam cli が samconfig.yaml を見つけるために必要なので checkout しておく
      - uses: actions/checkout@v6

      # Signin to AWS
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      # Docker build & push
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Generate the ImageUri
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            "${{ steps.login-ecr.outputs.registry }}/bruin-iwai/avshare3-sam"
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss' tz='Asia/Tokyo'}}-{{sha}}
      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}

      # SAM deploy
      - name: SAM setup
        if: github.event_name != 'pull_request'
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: SAM deploy
        if: github.event_name != 'pull_request'
        run: |
          sam deploy --parameter-overrides "ImageUri=${{ steps.meta.outputs.tags }}" "SecretVersionId=7ff5852d-b076-4735-8e72-2d759bf050ce"
